spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}?createDatabaseIfNotExist=true
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: user-service

  sql:
    init:
      mode: always